[theme]
base="light"
primaryColor="#000080"         # pink for buttons/sliders
backgroundColor="#ff3385"      # very light pink background
secondaryBackgroundColor="#36454F"  # slightly deeper pink for sidebar
textColor="#2c003e"            # deep purple text for contrast
font="sans serif"
