[theme]
base="light"
primaryColor="#000080"         # pink for buttons/sliders
backgroundColor="#ff99c2"      # very light pink background
secondaryBackgroundColor="#c0c0c0"  # slightly deeper pink for sidebar
textColor="#2c003e"            # deep purple text for contrast
font="sans serif"
