GEMINI_API_KEY = "AIzaSyATvjIkJjp5BxOGsP-8hY87sUo077Foz-I"

[google_oauth]
client_id = "453133241950-bsd0cqmtnvk4votich77vsaql0r2gg9i.apps.googleusercontent.com"
client_secret= "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"
[adzuna]
APP_ID = "e9f4af3e"
APP_KEY = "c94f08a47c82b3a943a67d2146f64d92"
